"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Report = {
  id: string;
  title: string;
  createdAt: string;
  generatedBy: {
    name: string;
    email: string;
  };
};

export default function ReportHistoryPage() {
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);

  const loadReports = async (currentPage = 1) => {
    const user = JSON.parse(localStorage.getItem("user") || "{}");

    if (!user.workspaceId) return;

    setLoading(true);

    try {
      const res = await fetch(`/api/reports?workspaceId=${user.workspaceId}&search=${encodeURIComponent(search)}&page=${currentPage}&limit=8`);
      const data = await res.json();

      if (data.success) {
        setReports(data.reports || []);
        setTotalPages(data.totalPages || 1);
      }
    } catch (error) {
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadReports(page);
  }, [page, search]);

  async function deleteReport(id: string) {
    const confirmed = window.confirm("Delete this report?");
    if (!confirmed) return;

    try {
      const res = await fetch(`/api/reports/${id}`, { method: "DELETE" });
      const data = await res.json();
      if (data.success) {
        setReports((current) => current.filter((item) => item.id !== id));
      }
    } catch (error) {
      console.error(error);
    }
  }

  return (
    <main className="min-h-screen bg-slate-50 p-4 sm:p-6 lg:p-8">
      <div className="mx-auto max-w-7xl">
        <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
          <div>
            <p className="text-sm font-medium uppercase tracking-[0.2em] text-slate-500">History</p>
            <h1 className="mt-1 text-3xl font-semibold text-slate-900">Report History</h1>
          </div>
          <div className="w-full max-w-sm">
            <input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search reports" className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm shadow-sm" />
          </div>
        </div>

        <div className="mt-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
          {loading ? (
            <div className="py-6 text-center text-slate-500">Loading report history...</div>
          ) : reports.length === 0 ? (
            <div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-8 text-center text-slate-500">No reports found.</div>
          ) : (
            <div className="overflow-x-auto">
              <table className="min-w-full">
                <thead className="bg-slate-50 text-left text-sm text-slate-500">
                  <tr>
                    <th className="px-4 py-3 font-medium">Title</th>
                    <th className="px-4 py-3 font-medium">Generated By</th>
                    <th className="px-4 py-3 font-medium">Created At</th>
                    <th className="px-4 py-3 font-medium text-center">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {reports.map((report) => (
                    <tr key={report.id} className="border-t border-slate-200 text-sm text-slate-700">
                      <td className="px-4 py-3 font-medium text-slate-900">{report.title}</td>
                      <td className="px-4 py-3">{report.generatedBy?.name || "Unknown"}</td>
                      <td className="px-4 py-3">{new Date(report.createdAt).toLocaleString()}</td>
                      <td className="px-4 py-3">
                        <div className="flex flex-wrap justify-center gap-2">
                          <Link href={`/reports/${report.id}`} className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-medium text-white transition hover:bg-slate-700">View</Link>
                          <a href={`/api/reports/download?id=${report.id}`} className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-medium text-slate-700 transition hover:bg-slate-100">Download</a>
                          <button onClick={() => deleteReport(report.id)} className="rounded-lg border border-rose-200 px-3 py-2 text-sm font-medium text-rose-600 transition hover:bg-rose-50">Delete</button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          <div className="mt-6 flex items-center justify-between">
            <p className="text-sm text-slate-500">Page {page} of {totalPages}</p>
            <div className="flex gap-2">
              <button disabled={page === 1} onClick={() => setPage((value) => Math.max(1, value - 1))} className="rounded-lg border border-slate-200 px-3 py-2 text-sm disabled:opacity-50">Prev</button>
              <button disabled={page === totalPages} onClick={() => setPage((value) => value + 1)} className="rounded-lg border border-slate-200 px-3 py-2 text-sm disabled:opacity-50">Next</button>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}